server:
  port: 8080

spring:
  application:
    name: db-migration-liquibase
  datasource:
    url: jdbc:postgresql://localhost:5432/liquibase_migration
    username: postgres
    password: 1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  liquibase:
    enabled: false

